version: "2"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb
